### ISSUE TITLE
Fotos para decir CTM en portada

### ISSUE THREAD

**Issue by ivangelion68** [antronio/elantro-ctm#10]
Se requiere que el cuadro que enlaza al tema Fotos para decir CTM se encuentre en la portada. Da lo mismo la posición del cuadro, sólo que esté en portada sería genial.

**Comment by EstebanForge** [comment]
Andando.

Eventualmente vamos a hacer que saque las fotos directo de FPDCTM como antes, o bien, subir un set de memes en torno a ElAntro (como el que se subió)... lo que nos daría control para hacer que el sitio vuele en el home y, de paso, no ocurran accidentes.
