### ISSUE TITLE
Error en vista de cabecera

### ISSUE THREAD

**Issue by ivangelion68** [antronio/elantro-ctm#11]
![image](https://user-images.githubusercontent.com/4099643/82470875-e7ea8d80-9a93-11ea-915f-09ccf427b651.png)

**Comment by EstebanForge** [comment]
XF2 es super lento cuando quieres hacer un cambio en un template (eso incluye js y css).

Cada vez que haces uno, el sistema de XF se pone a re-hacer todos y cada uno de los templates a un caché local de archivos.

Lo siento. y gracias por el aviso.
Está resuelto.

PD: y no hay _platita_ para un staging.
