### ISSUE TITLE
Boton para navegar desde un tema a otros foros

### ISSUE THREAD

**Issue by PipeRocks** [antronio/elantro-ctm#12]
Hola. 
Antes habia un boton para navegar desde un tema a otros foros. Para mi era muy util. No se si para el resto.

![qvuelvaelmenu](https://user-images.githubusercontent.com/65687308/82504865-63ffc800-9aca-11ea-89e9-afe2d5430d03.png)

**Comment by TCattd** [comment]
Esa característica de llamaba Quick Navigation.

No existe en XF2 (como pudiste ver).

Detalles: https://xenforo.com/community/threads/is-there-a-quick-navigation-menu-equivalent-in-xf2.140440/

Dudo que sea algo en prioridad para replicar.
Y como dijimos en un principio, no nos interesa clonar 1:1 lo que había en XF1 tampoco.

Lo siento.
