### ISSUE TITLE
Iconos de Reacciones personalizados

### ISSUE THREAD

**Issue by Don-Spyrox** [antronio/elantro-ctm#13]
Los iconos de reacciones (me gusta, no me gusta, etc), podrian cambiarse a alguno más personalizado, bajo votacion del la elite.

El formato de la imagen es bastante simple, es una imagen completa con todas las reacciones, y asumo que al reaccionar, el sistema mueve solo la misma imagen a una posicion X e Y personalizada.
El formato de imagen se puede modificar a gusto, manteniendo el PNG transparente y generando una revision aceptable, sin bordes blancos. 
https://www.antronio.cl/styles/default/xenforo/reactions/emojione/sprite_sheet_emojione.png

Un ejemplo:

https://i.imgur.com/Lj9e3VB.png

**Comment by EstebanForge** [comment]
Duplicado https://github.com/antronio/elantro-ctm/issues/4
