### ISSUE TITLE
Sitio "instalable" como app móvil

### ISSUE THREAD

**Issue by EstebanForge** [antronio/elantro-ctm#14]
Estilo PWA (aunque XF2 no lo soporta por completo).

Esto para quienes usan el sitio el móvil, y no quieren usar Tapatalk.

Necesitamos iconos decentes para Android e iOS.
No soy diseñador.

Si alguien quiere cooperar con esto (iconos) bienvenido sea.
PNG 1024x1024 (nosotros reajustamos al resto de los tamaños). Icono se debe ver bien hasta en 48x48 pixels. 

Seguir la línea de iconos de iOS para iOS:
https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/

E iconos adaptativos para Android en modo circular. Ver: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive y https://developer.android.com/google-play/resources/icon-design-specifications

**Comment by pripboy** [comment]
Dos versiones
![concirculo](https://user-images.githubusercontent.com/65727716/82586553-c063f580-9b65-11ea-8ba3-efc64dd0aac9.png)
![sincirculo](https://user-images.githubusercontent.com/65727716/82586554-c0fc8c00-9b65-11ea-9b10-aac8430ee19e.png)

**Comment by EstebanForge** [comment]
@pripboy agradecido por la ayuda acá.

Agregado el manifest y lo necesario para que esto funcione:
![Screenshot_20200522-104253](https://user-images.githubusercontent.com/1696145/82680411-37f35c80-9c1a-11ea-85e9-a1a5564ac7d7.png)

En Android es automático.

En iOS deben hacerlo manual así: 
![1_4yTqRXTD-GK2GOmqblGhxA](https://user-images.githubusercontent.com/1696145/82680691-a59f8880-9c1a-11ea-9b7f-76ba6cb45640.png)
...porque: Apple.

Detalle en Android:

El ícono (con transparencia, lo que está fuera del círculo debe ser transparente), se ve más pequeño que el default de Android (íconos adaptativos). Ver:
![Screenshot_20200522-104742](https://user-images.githubusercontent.com/1696145/82680457-493c6900-9c1a-11ea-8dff-33d689247151.png)

@pripboy ¿Me puedes ayudar con eso, por favor?.

Al final abajo en esta URL https://developer.android.com/google-play/resources/icon-design-specifications tienes templates para bajar https://tppr.me/asSYQ por si te sirven.
De esa forma, me imagino, es más sencillo adaptar el círculo al que Android espera.

**Comment by pripboy** [comment]
@TCattd me quedó el círculo un poco más pequeño, ahora no debería tener problemas
![concirc](https://user-images.githubusercontent.com/65727716/82692881-7eeb4d00-9c2e-11ea-9c31-3bfd60209c6a.png)

**Comment by EstebanForge** [comment]
@pripboy no se si GitHub le saca la transparencia al PNG o no la pusiste.

La idea es que toda la parte de fuera sea transparente https://tppr.me/bnR50 please.

Si es GitHub el problema, puedes zipearlo y dejar un link de wetransfer.com acá, por favor?
O enviarlo por email: esteban (arroba) attitude.cl

¡Gracias!

**Comment by pripboy** [comment]
@TCattd Según las especificaciones de Google debe ser el tamaño completo cuadrado, sin transparencias. Sólo se pide que esté dentro de los márgenes de la plantilla

**Comment by EstebanForge** [comment]
Hmmm. Deja probar entonces. Aviso.

**Comment by EstebanForge** [comment]
Tenías razón, @pripboy

Pero ojo, mira: https://tppr.me/cbmxn
Aún se ven íconos mal cortados cuando van a otras resoluciones.

Eso si, yo hice los cortes automáticos con https://app-manifest.firebaseapp.com/ podría haber sido eso.
¿Habré sido yo con eso?.

Más info de íconos adaptativos para PWA https://web.dev/maskable-icon/?utm_source=devtools

Estos son los tamaños que estamos usando:
```
  "icons": [
    {
      "src": "elantro/images/icons/icon-72x72.png",
      "sizes": "72x72",
      "type": "image/png"
    },
    {
      "src": "elantro/images/icons/icon-96x96.png",
      "sizes": "96x96",
      "type": "image/png"
    },
    {
      "src": "elantro/images/icons/icon-128x128.png",
      "sizes": "128x128",
      "type": "image/png"
    },
    {
      "src": "elantro/images/icons/icon-144x144.png",
      "sizes": "144x144",
      "type": "image/png"
    },
    {
      "src": "elantro/images/icons/icon-152x152.png",
      "sizes": "152x152",
      "type": "image/png"
    },
    {
      "src": "elantro/images/icons/icon-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "elantro/images/icons/icon-384x384.png",
      "sizes": "384x384",
      "type": "image/png"
    },
    {
      "src": "elantro/images/icons/icon-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ],
```

**Comment by EstebanForge** [comment]
No era tan automático @pripboy

El caché de mi equipo (Chrome) hacía que se viera aún el ícono antiguo.
Probé en otro, y se ve el png nuevo, pero... Android lo auto-adapta simplemente metiéndolo en un círculo bien feo.

Ver: https://tppr.me/cPGwg
(Desde WhatsApp, por eso la calidad, pero se ve bien fuera del cuadrado, no pixelead).

A diferencia de si le pongo el círculo transparente directamente, como lo hice la primera vez.
Ahí Android si lo sirve como un círculo sin el fondo.

**Comment by EstebanForge** [comment]
El problema sería otros equipos, como los Samsung, que usan otra forma distinta al círculo para los iconos adaptativos de Android.

No se que hacer acá la verdad. No lo sé.

¿Ideas?

**Comment by pripboy** [comment]
Y ocupar la opción 2 enviada?

**Comment by pripboy** [comment]
> Tenías razón, @pripboy
> 
> Pero ojo, mira: https://tppr.me/cbmxn
> Aún se ven íconos mal cortados cuando van a otras resoluciones.
> 
> Eso si, yo hice los cortes automáticos con https://app-manifest.firebaseapp.com/ podría haber sido eso.
> ¿Habré sido yo con eso?.
> 
> Más info de íconos adaptativos para PWA https://web.dev/maskable-icon/?utm_source=devtools
> 
> Estos son los tamaños que estamos usando:
> 
> ```
>   "icons": [
>     {
>       "src": "elantro/images/icons/icon-72x72.png",
>       "sizes": "72x72",
>       "type": "image/png"
>     },
>     {
>       "src": "elantro/images/icons/icon-96x96.png",
>       "sizes": "96x96",
>       "type": "image/png"
>     },
>     {
>       "src": "elantro/images/icons/icon-128x128.png",
>       "sizes": "128x128",
>       "type": "image/png"
>     },
>     {
>       "src": "elantro/images/icons/icon-144x144.png",
>       "sizes": "144x144",
>       "type": "image/png"
>     },
>     {
>       "src": "elantro/images/icons/icon-152x152.png",
>       "sizes": "152x152",
>       "type": "image/png"
>     },
>     {
>       "src": "elantro/images/icons/icon-192x192.png",
>       "sizes": "192x192",
>       "type": "image/png"
>     },
>     {
>       "src": "elantro/images/icons/icon-384x384.png",
>       "sizes": "384x384",
>       "type": "image/png"
>     },
>     {
>       "src": "elantro/images/icons/icon-512x512.png",
>       "sizes": "512x512",
>       "type": "image/png"
>     }
>   ],
> ```

Y la opción `"purpose": "maskable"` ?

**Comment by EstebanForge** [comment]
Eso era @pripboy 
Me faltó leer :B

Estaba usando la segunda opción.
Ahora se ve bien: 

![WhatsApp_2020-05-22 14-38-05@2x](https://user-images.githubusercontent.com/1696145/82699055-ee1a6e80-9c39-11ea-8e5c-7455e7d57f56.jpg)

(De WhatsApp, por eso la resolución. Mi fono aún ve el ícono viejo. De ahí reviso eso)

¡Gracias!
