### ISSUE TITLE
Navegación dentro de un tema, versión móvil

### ISSUE THREAD

**Issue by EstebanForge** [antronio/elantro-ctm#15]
Botones bajo el tema https://imgur.com/a/ZAz4GIr

Ver si es posible replicar en la parte superior de un tema también.

¿Problema de espacio en móvil?.

Revisar templates. ¿Posibilidad de clonar existente?.

**Comment by pripboy** [comment]
El alto y ancho se pueden modificar en el siguiente selector

`#XF .pageNavSimple-el`

El cambio a diseño móvil lo hace con el media-query a 650px, ahí se podría agregar / modificar:

`#XF .pageNavSimple-el{
padding: 5px 8px;
}`

Con eso se reduce el espacio utilizado

**Comment by EstebanForge** [comment]
El problema es espacio en general. El espacio vertical que consume tener otra cosa más ahí justo antes del contenido del post y sus mensajes.
Por eso los desarrolladores lo tienen oculto por default en móvil.

Pero se puede traer de vuelta fácil:
https://xenforo.com/community/threads/xf2-add-page-numbers-at-top-of-forum-in-mobile-version.148865/post-1328833

Aplicado y andando.

![Google Chrome_2020-05-22 11-13-22@2x](https://user-images.githubusercontent.com/1696145/82682445-455e1600-9c1d-11ea-93f2-902a2b235a2f.jpg)
