### ISSUE TITLE
Quoteo deformado al mostrar contenido ignorado

### ISSUE THREAD

**Issue by prpdesigns** [antronio/elantro-ctm#16]
Cuando se da clic para mostrar el contenido ignorado de un usuario y este contenido está dentro de un quoteo, se deforma el quote, dejando contenido fuera de él.

Esto no pasaría si al darle clic a "Mostrar contenido ignorado" se eliminara el div de aviso 'messageNotice--ignored'

Dejo imágenes de ejemplo:

Quote con contenido ignorado
![quote-ignorado](https://user-images.githubusercontent.com/6282732/82609617-d801a500-9b8a-11ea-8848-be8e643adb72.png)

Quote mostrando el contenido, se deforma
![quote-mal](https://user-images.githubusercontent.com/6282732/82609653-ea7bde80-9b8a-11ea-922d-836724290767.png)

Como debería ser, eliminando el aviso de contenido ignorado al presionar el link
![quote-bien](https://user-images.githubusercontent.com/6282732/82609688-fff10880-9b8a-11ea-88dc-42bf4da77622.png)

**Comment by prpdesigns** [comment]
Solución con jQuery:

`$( ".showIgnoredLink" ).click(function() {
  $(this).parent().hide();
});`

**Comment by EstebanForge** [comment]
¡Gracias!
