### ISSUE TITLE
Wiki antroniana

### ISSUE THREAD

**Issue by pripboy** [antronio/elantro-ctm#19]
Se puede recuperar? o se tiene que crear desde cero?

**Comment by EstebanForge** [comment]
Ok @pripboy , sorry por la demora.
Tenía que preguntar que opciones teníamos acá, antes.

El plugin pegó en un bug al migrar a XF2 y tratar de restaurar el contenido desde la Wiki anterior.
El desarrollador es el mismo.

Lamentablemente, para poder volver a tener una oportunidad de re-importar todo lo de la Wiki v1 a la Wiki v2, tendríamos que pasar por el proceso de volver a convertir XF1 a XF2.
O sea, tomar un respaldo viejo de XF1, montarlo en un server aparte (o en un pc, local), convertir a XF2 ahí y luego probar de nuevo la migración de la Wiki de v1 a la v2.

El pero acá son dos cosas: tamaño y tiempo.

La DB del sitio pesa más de 20 gigas.

No hay tiempo para hacer esto. Ni CTO ni yo tenemos el tiempo para pegarnos de nuevo una migración (en local) de ese tamaño de DB, para ver si ahora el bug en el import de la Wiki está resuelto o no (cosa que no es segura tampoco).

Luego, si esa migración en local va bien, tendríamos que exportar las tablas de la DB solo de la Wiki a la DB en producción, y esperar que la Wiki vea esos cambios (asumiendo que solo la tabla de las páginas de la Wiki es la que tenemos que mover) y que funcione correctamente todo.

No hay tiempo.

Ahora, tengo lo segundo mejor que puedo entregar a la comunidad. Lo voy a dejar adjunto acá.

Es un CSV para abrir en Excel o similar, con todas las páginas de la Wiki v1.
Es un export directo de la tabla de la DB con todas las páginas. 433 páginas en total.

Descarga:
[Wiki-elantro-v1.zip](https://github.com/antronio/elantro-ctm/files/4703086/Wiki-elantro-v1.zip)

Dentro verán las siguientes columnas, que son las relevantes:

- page_slug. Es el link url: https://tppr.me/54whn ideal mantenerlo tal como viene desde el Excel. De esa forma, la URL de la Wiki se mantendrá con respecto a como estaba, y los enlaces entre páginas que tenían hechos seguirán funcionando. También ayudará a que las URLs indexadas en Google, de la Wiki, sigan funcionando.

- page_name. El nombre de la entrada de la Wiki. Lo mismo que con el page_slug, ideal respetar el mismo nombre que ya había.

- page_content. Esto es el contenido de la página, en formato BBcode. Aquí literalmente pueden tomar el contenido de esa celda y copiar-pegar en la nueva entrada de la Wiki. Debería funcionar, sin cambios.

- page_parent. Si una entrada era hija de otra página, aquí verán la ID de esa página padre. Debería coincidir con otra página del csv en relación a su columna page_id.

Con eso podrían re-crear 100% igual lo que había en la Wiki v1 antes de la migración a XF2. Sin tanto problema, copiando-pegando.

Desde ya lo siento por no poder hacer esto automático. El tiempo es un inconveniente acá.

Si quieren coordinar esa re-creación de la Wiki acá mismo, bienvenido sea. Pueden usar este issue.
Si quieren hacerlo en un tema allá en el sitio, simplemente créalo @pripboy , y lo dejamos enlazado acá. Tampoco hay inconvenientes.

Si necesitan ayuda con algo más, avisan y vemos que podemos hacer.

**Comment by EstebanForge** [comment]
"How to".

Crear página, y respetar el page_slug y page_title. Formato BBcode. Configurar bien la página padre, según corresponda.

![Google Chrome_2020-05-29 12-48-53@2x](https://user-images.githubusercontent.com/1696145/83284562-d186b500-a1aa-11ea-81ef-99b0953517b4.jpg)

Ahora, editar la página creada:

![Google Chrome_2020-05-29 12-30-19@2x](https://user-images.githubusercontent.com/1696145/83283198-cf235b80-a1a8-11ea-9740-2623566b0292.jpg)

Activar el switch para ver el contenido del post como BBcode primero, y luego pegar el texto desde el Excel.

Copiar-pegar el contenido de la celda page_content de la fila correspondiente.

Luego volver a usar el switch para ver el preview de la página. Deberían verla tal cual como estuvo antes.

![Google Chrome_2020-05-29 12-33-57@2x](https://user-images.githubusercontent.com/1696145/83283146-badf5e80-a1a8-11ea-90f0-41df41d268ac.jpg)

Finalmente, guardar.

Índice restaurado:

![Google Chrome_2020-05-29 12-35-29@2x](https://user-images.githubusercontent.com/1696145/83283256-e9f5d000-a1a8-11ea-8dcf-531030f245d1.jpg)

**Comment by EstebanForge** [comment]
Restauradas las páginas de la ID 1 a la 7. Aquellas están listas. Como demo de la recuperación de contenido desde el csv/xlsx.

**Comment by pripboy** [comment]
Gracias!

**Comment by pripboy** [comment]
Algunos comentarios respecto a la wiki:

1. La barra lateral con el menú de navegación se va a hacer inmensa a medida que se vaya agregando cada página (considerando que son más de 250 páginas). Para esto tengo 2 posibles soluciones: Recomiendo quitar la barra lateral en las páginas (ej.- https://www.antronio.cl/wiki/antidoto/ y la navegación sería por el "breadcrumb" superior), o:
2.- Actualmente la categoría principal es el Inicio y de él se desprenden todas las demás páginas. Recomiendo que las páginas que tengan páginas hijas no estén debajo del Inicio (sin padre), o si no la lista de páginas (https://www.antronio.cl/wiki/special/pages) sólo mostrará la categoría Inicio (se añade un cuadro por cada letra) Esto también afecta a cómo se muestra la barra lateral del menú y podría solucionar lo anterior.

**Comment by EstebanForge** [comment]
Ahí saqué el sidebar en el index.

Teniendo el acceso al listado de páginas en ese punteo del inicio, sirve de todos modos.

Gracias @pripboy ;)

Cuando tengan listo esto, avisan y cerramos el issue no más, please. Quedo atento a ustedes ahí.

**Comment by EstebanForge** [comment]
Excelente @pripboy :)

¡Muchas gracias!
