### ISSUE TITLE
Medallas Galaga deforman el diseño (en móvil)

### ISSUE THREAD

**Issue by pripboy** [antronio/elantro-ctm#23]
Cuando el usuario tiene demasiadas medallas, el header con la info del usuario se deforma en la versión móvil:

Post de ejemplo: https://www.antronio.cl/threads/seria-bueno-hacer-un-foro-antronio-alternativo.1322685/post-26423377

![muestra-01](https://user-images.githubusercontent.com/65727716/83934705-de923e00-a780-11ea-8b5a-555fa60534b3.jpg)
![muestra-02](https://user-images.githubusercontent.com/65727716/83934707-e3ef8880-a780-11ea-85e2-b6934d334b38.jpg)

La solución es añadir la siguiente regla css:

`
@media (max-width: 650px)
.message:not(.message--forceColumns) .message-userExtras {
max-width:49%;
}
`
Así quedaría:

![muestra-03](https://user-images.githubusercontent.com/65727716/83934753-3cbf2100-a781-11ea-81a6-a175210f795d.jpg)

**Comment by EstebanForge** [comment]
Gracias nuevamente, @pripboy
