### ISSUE TITLE
Post Reply - Funcionamiento inconsistente

### ISSUE THREAD

**Issue by trukex** [antronio/elantro-ctm#24]
Estimados,

esto solo me pasa en el foro Futbol. Al enviar un nuevo posteo, se queda "enviando" aproximadamente 15 segundos y luego no pasa nada, no borra el cuadro de texto ni informa que el post fue exitoso, lo que provoca que se generen doble post.

Se escribe el texto y presiona post reply
![2020-06-06_20-26-50](https://user-images.githubusercontent.com/34099810/83957369-f5df3300-a835-11ea-93e8-7e9ef0f6fa72.png)

Aparece la barra de progreso
![2020-06-06_20-27-09](https://user-images.githubusercontent.com/34099810/83957370-f677c980-a835-11ea-8cde-8e60011f2484.png)

No cambia nada y al presionar F5 aparece el post nuevo y el cuadro de texto incólume contiene aun el texto como si no se hubiera incorporado al tread.

![2020-06-06_20-28-19](https://user-images.githubusercontent.com/34099810/83957371-f7106000-a835-11ea-87e8-448739e394fd.png)

Como comenté esto solo lo he detectado en el foro futbol, acabo de escribir en el foro de soporte donde TC creó el tema de GitHub y el posteo funcionó sin ningun problema.

**Comment by EstebanForge** [comment]
Duplicado de https://github.com/antronio/elantro-ctm/issues/22

Son los problemas de server que ya estamos viendo.
Paciencia, por favor.

Gracias.
