### ISSUE TITLE
Error al tratar de unirse al Discord desde el MO

### ISSUE THREAD

**Issue by pripboy** [antronio/elantro-ctm#26]
El botón para unirse al discord arroja un error, prueba realizada en Chrome 83, windows 10

Al presionar el botón, en la consola aparece el siguiente error:

`Access to XMLHttpRequest at 'https://discord.gg/h4PqCgJ' from origin 'https://www.antronio.cl' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

![error-1](https://user-images.githubusercontent.com/65727716/84716255-99b89500-af40-11ea-8c7a-9219626d578f.jpg)

También aparece una advertencia al cargar el chat, no sé si tendrá que ver:

`DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/@widgetbot/html-embed.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

![error-2](https://user-images.githubusercontent.com/65727716/84716408-00d64980-af41-11ea-9831-5bdd174403af.jpg)

**Comment by EstebanForge** [comment]
El primer error debería estar resuelto. Al menos acá, no puedo reproducirlo.
Me confirmas, please, si está todo ok por tu lado.

El segundo no tiene que ver con ElAntro en si.

**Comment by pripboy** [comment]
> El primer error debería estar resuelto. Al menos acá, no puedo reproducirlo.
> Me confirmas, please, si está todo ok por tu lado.
> 
> El segundo no tiene que ver con ElAntro en si.

Ahora si está funcionando correctamente el botón, confirmado en PC y smartphone

**Comment by EstebanForge** [comment]
Gracias!
