### ISSUE TITLE
Páginas vacías

### ISSUE THREAD

**Issue by ivangelion68** [antronio/elantro-ctm#28]
![image](https://user-images.githubusercontent.com/4099643/90338761-f1fc2980-dfb9-11ea-8e3b-899c21c405b0.png)

**Comment by pripboy** [comment]
Eso pasa cuando el único mensaje de la página es de un usuario al que tienes ignorado.

**Comment by ivangelion68** [comment]
> Eso pasa cuando el único mensaje de la página es de un usuario al que tienes ignorado.

Tienes toda la razón... cierro este requerimiento
