### ISSUE TITLE
Reacciones, ajustar al estilo de ElAntro

### ISSUE THREAD

**Issue by EstebanForge** [antronio/elantro-ctm#4]
Como dice el título.

Ver cuales son las 5 reacciones más importantes (aparte del "se agradece"). No es la idea tener un selector de reacciones repleto de caritas tampoco.

¿Decidir con votación las 5 reacciones finales?

**Comment by antrolio** [comment]
(copio del otro issue para mantener el orden)
Una de las tantas cosas que se han hablado en el foro es que las reacciones sean personalizadas, en otras palabras, que las imágenes de éstas sean imágenes que representen sensaciones del forazo. 
Por poner un ejemplo, abusheo con la cara de desmond, me enbubalona con la cara de un mono narigón, de manera que se rescate lo mas divertido del foro. En cualquier caso yo sugiero hacer una encuesta para que se queden los mejores aportes.
Personalmente escribí un pequeño código en jquery que hace la pega, por lo que implementar algo de este nivel no debiera ser complicado. Comparto un poco la pega que hice:
Las reacciones se encuentran en la siguiente clase: `.reaction`, son 6 en total y tenemos una segunda subclase que te divide cada reaccion de la siguiente forma `.reaction--3`, donde 3 es el número de la reacción que quiero modificar.
De hecho, con un simple código jquery se puede modificar, por ejemplo, para la reacción 3 `$(".reaction.reaction--3 img").attr("src","url-imagen")`

**Comment by EstebanForge** [comment]
No se necesita desarrollar nada acá. XF2 tiene la opción de subir tus propios emoticons para un set de reacciones.

Lo que tenemos que ver es cuales (emoticons) son candidatos a quedar ahí, y quizás hacer votación para elegir unas 5, tope, que queden en el set final disponible.
