### ISSUE TITLE
Colores

### ISSUE THREAD

**Issue by antrolio** [antronio/elantro-ctm#7]
Diría que el 99% de los usuarios odiamos los nuevos colores con tonos azules, pripboy hizo un gran trabajo en hacer una modificación del css para que recuperemos los viejos colores, esta pega ya está hecha y prácticamente sería un copiar y pegar. Adjunto el css
`html {
    color: #dadada
}
.p-sectionLinks {
    background: #191919;
    border-bottom:1px solid #333
}
.notice.notice--primary {
    color:#dadada;
    background:#444
}
html[data-focus-bg='1'], html[data-focus-bg='1'] .block-header, html[data-focus-bg='1'] .node-icon i {
    background-image:none
}
.block-header {
    background:#444;
    border: 0px solid #555
}
.block-container {
    color:#ccc;
    background:#282828;
    border: 0px solid #444
}
.message-attribution, .shareButtons-button, .node-description, .p-description {
    color:#888;
}
.block-footer, .porta-article-item .porta-article-date .porta-date-block {
    color:#aaa;
    background: #353535;
    border-top: 1px solid #444
}
.focus-content, .p-nav-list .p-navEl.is-selected {
    background: #191919
}
.block-minorHeader, .p-body-sidebar .block-row:not(:last-child) {
    border-bottom: 1px solid #444
}
.block-minorHeader {
    color:#ddd
}
.contentRow-minor, .pairs>dt {
    color:#777
}
.p-body-header {
    color: #dadada;
    background: #222;
    border: 0px solid #444
}
.focus-grid .block--category .node-body {
    color: #dadada;
    background: #282828;
    border: 0px solid #444;
}
html[data-logged-in='true'] .node--unread .node-title::before {
    background: #b22222;
    background: var(--new-badge-background, #b22222)
}
.input {
    color: #dadada;
    background: #353535;
    border: 1px solid #555;
    border-bottom-color: #494949
}
.overlay-title {
    color: #ddd;
    background: #444;
    border-bottom: 1px solid #494949
}
.message-cell.message-cell--user, .message-cell.message-cell--action, .message-responseRow {
    background: #333;
    border-right: 1px solid #494949
}
.fr-toolbar {
    color: #dadada;
    background: #333;
    border: 1px solid #555;
    border-top: 3px solid #999
}
.fr-toolbar .fr-command.fr-btn, .fr-popup .fr-command.fr-btn, .fr-desktop .fr-command:hover, .fr-desktop .fr-command:focus, .fr-desktop .fr-command.fr-btn-hover, .fr-desktop .fr-command.fr-expanded {
    color: #dadada
}
.fr-box.fr-basic .fr-wrapper {
    background: #333;
    border: 1px solid #555
}
.tabs--standalone {
    border: 0px solid #444;
    color: #dadada;
    background: #333
}
.tabs--standalone .tabs-tab.is-active {
    color: #999;
    border-color: #999
}
.p-breadcrumbs-wrap, #XF .pageNav-jump, #XF .pageNav-page, #XF .pageNavSimple-el {
    color: #e1e1e1;
    background-color: #333
}
.block-filterBar {
    color: #dadada;
    background: #444;
    border-bottom: 1px solid #555
}
.block--messages .message, .block--messages .block-row {
    color: #dadada;
    background: #222;
    border: 0px solid #444
}
#siropuChatTabs {
    border-bottom: 1px solid #555;
}
#siropuChatEditor .fr-toolbar {
    border-top: 1px solid #555;
    border-bottom: 1px solid #555
}
#siropuChatEditor .fr-wrapper {
    background: #222
}
.menu-arrow {
    border-bottom-color: #999
}
.menu-content {
    color: #dadada;
    background: #282828;
    border-top: 3px solid #999
}
.menu-tabHeader {
    color: #dadada;
    background: #444;
    border-bottom: 1px solid #555
}
.menu-tabHeader .tabs-tab.is-active {
    color: #999;
    border-color: #999
}
.input[readonly], .input.is-readonly, .colorPickerBox, .inputGroup.inputGroup--joined .inputGroup-text {
    color: #ababab;
    background: #383838;
    border: 1px solid #555
}
.focus-search-menu {
    color: #dadada;
    background: #494949
}
.focus-search-menu::after {
    border-bottom-color: #494949
}
.focus-search-menu .menu-footer {
    background: #333;
    border-top: 1px solid #494949;
}
.siropuChatDateTime {
    color:#999
}
.menu-header {
    color: #dadada;
    background: #353535;
    border-bottom: 1px solid #494949
}
.menu-row.menu-row--clickable:hover {
    background:#444
}
.menu-row.menu-row--alt {
    color: #dadada;
    background: #353535;
}
.menu-footer {
    color: #ababab;
    background: #333;
    border-top: 1px solid #494949
}
#XF .pageNav-jump:hover, #XF .pageNav-page:hover, #XF .pageNavSimple-el:hover, #XF .pageNav-jump:active, #XF .pageNav-page:active, #XF .pageNavSimple-el:active {
    background-color: #3c3c3c
}
.structItemContainer-group--sticky::before, .structItemContainer-group--sticky::after {
    background: #353535;
    border: 1px solid #424242
}
.block-body>.node:nth-of-type(even), .structItemContainer-group>.structItem--thread:not(.is-highlighted):not(.is-moderated):not(.is-mod-selected):nth-of-type(even) {
    background-color: #323232
}
.structItem {
    border-top: 1px solid #424242
}
.structItem-minor {
    color: #777
}
.structItem-pageJump a {
    color: #ababab;
    background: #353535;
    border: 1px solid #4f4f4f
}
.structItem-minor dd {
    color:#dadada
}
.button.button--link, a.button.button--link {
    border-color: #646464;
    color: #e2e2e2;
    background:#2d2d2d
}
.button.button--link:hover, a.button.button--link:hover, .button.button--link:active, a.button.button--link:active, .button.button--link:focus, a.button.button--link:focus {
    background: #383838;
}
.tagItem {
    color: #ababab;
    background: #353535;
    border: 1px solid #4f4f4f
}
.bbCodeBlock {
    color: #ababab;
    background: #353535;
    border-color: rgba(218, 218, 218, 0.35);
    border-left: 3px solid #ababab;
}
.bbCodeBlock-title {
    color: #ababab
}
.bbCodeBlock-expandLink {
    background: linear-gradient(to bottom, rgba(53, 53, 53, 0) 0%, #222 80%)
}
.bbCodeBlock-expandLink a {
    color: #ffd700;
}
.message-signature {
    color: #777;
    border-top: 1px solid #494949
}
.button, a.button {
    color: #4f4f4f;
    background: #d6d6d6
}
.formSubmitRow-bar {
    background: #4f4f4f;
    border-top: 1px solid #555;
}
.formRow>dt {
    background: #353535;
    border-color: #494949;
}
.inputChoices-explain, .formRow .formRow-explain {
    color:#777
}
.formRow.formRow--fullWidth+.formRow, .formRow+.formRow.formRow--fullWidth, .formRow.formRow--fullWidth+*>.formRow:first-of-type, .formRow+*>.formRow.formRow--fullWidth:first-of-type, .formRowSep {
    border-top: 1px solid #494949;
}
.block-formSectionHeader {
    color: #919191;
    border-top: 1px solid #4f4f4f;
    border-bottom: 1px solid #424242
}
.input[disabled], .input.input--number[disabled]~.inputNumber-button {
    color: #777;
    background: #3c3c3c
}
.fr-popup {
    color: #dadada;
    background: #353535;
    border: 1px solid #555;
    border-top: 3px solid #999
}
`

**Comment by EstebanForge** [comment]
Primero que todo, lo que te responderé acá, ya cuenta con un pre-juicio por lo que comentaste en tu issue de los emoticons.

En segundo lugar, creo que olvidaste esto: https://tppr.me/N13Dg

Tercero: ¿99% de los usuarios odian los colores? ¿dónde está esa encuesta y cuál es la muestra de usuarios?.

Cuarto: creo que debes desactivar el addon/style que hizo aquel usuario, y ver tu mismo como están los colores del sitio hoy (desde hace unos días ya).
No están 100% igual que antes, pero se ha bajado el tono "azul-grisáceo" de varias parte del theme utilizado ahora.

Es más: el color de fondo de los posts ahora es idéntico al anterior usado en XF1, y la fuente dentro de los mensajes es del mismo color y tamaño también.
Otra más: el fondo del sitio es el mismo de antes. Se usa la misma imagen de patrón.

Si estás usando el addon de ese usuario, dudo mucho que te hayas enterado de esos cambios.
Por favor, hazlo. Luego, si aún quieres, abres otro issue con detalles puntuales que mejorar dentro de los colores actuales del sitio. Alguna zona a la que mejorar el contraste, o cosas así.

No otro issue "con un copien y peguen esto para volver a como estaba". Eso no va a funcionar esta vez.

Lo siento.
