### ISSUE TITLE
Recuperar emoticonos clásicos

### ISSUE THREAD

**Issue by antrolio** [antronio/elantro-ctm#8]
Un gran porcentaje de usuarios se ha visto menoscabado por la cantidad de emoticonos homosexuales que hay en el foro. Personalmente que hayan más emoticonos no le veo el problema, pero me parece una aberración que emoticonos clásicos como :eek: se vean reemplazados por los nuevos.

**Comment by EstebanForge** [comment]
No entiendo como algo como esto https://tppr.me/ifBa5 puede ser "más homosexual" que esto https://tppr.me/cDIWI

De hecho, no entiendo cómo un emoticon (sobre todo los primeros) puede ser "homosexual".

Pésima elección de palabras para intentar mostrar tu punto, estimado. Pésima elección.

Advertimos que seríamos densos acá con las reglas que solicitamos respetar https://github.com/antronio/elantro-ctm#normas-de-convivencia
No estamos para perder tiempo acá. No en GitHub.

Dicho eso, y como extra (por aportar con otros issues), respondo a tu problema:

El tema es super simple. ¿No les gustan los emoticons default de XF2?, no los usen. Los antiguos siguen ahí de todos modos, listos para ser usados.

Los emoticons viejos y clásicos no se han perdido (como dejas implícito en tu título). Siguen ahí disponibles para su uso.
